version: '3'
volumes:
  cache:
    driver: local
  minio-data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: project
    depends_on:
      - minio
      - redis
      - postgres
  redis:
    image: "redis:latest"
    ports:
      - '6379:6379'
    command:
      redis-server --save 20 1 --loglevel warning --requirepass YWZpd2hmdXdlaGZld2ZlZm52ZGhmc3V0Zg==
    volumes:
      - cache:/data
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgresPassword
    ports:
      - "5433:5432"
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio